baseurl:
permalink: "/news/:year/:month/:day/:title/"
latest_download_kouchat_desktop: "https://github.com/blurpy/kouchat/releases/download/kouchat-1.3.0/kouchat-1.3.0.jar"
latest_download_kouchat_android: "https://github.com/blurpy/kouchat-android/releases/download/kouchat-android-1.1.1/kouchat-android-1.1.1.apk"
user_guide_console: "help/user-guide/console/"
user_guide_desktop: "help/user-guide/desktop/"
user_guide_android: "help/user-guide/android/"
