baseurl:
permalink: "/news/:year/:month/:day/:title/"
latest_download_kouchat_desktop: "https://github.com/blurpy/kouchat/releases/download/kouchat-1.2.0/kouchat-1.2.0.jar"
latest_download_kouchat_android: "https://github.com/blurpy/kouchat-android/releases/download/kouchat-android-1.0.2/kouchat-android-1.0.2.apk"
